default: &default
  secret_key_base: <%= Figaro.env.secret_key_base! %>
  database_name: <%= Figaro.env.database_name! %>
  database_username: <%= Figaro.env.database_username! %>
  database_password: <%= Figaro.env.database_password! %>
  database_host: <%= Figaro.env.database_host! %>
  database_port: <%= Figaro.env.database_port! %>
  bugsnag_api_key: <%= Figaro.env.bugsnag_api_key! %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
